<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '公司介绍';
$typeArr[3] = '文化理念';
$typeArr[4] = '组织架构';
$typeArr[5] = '企业优势';
$typeArr[6] = '新闻资讯';
$typeArr[7] = '公司新闻';
$typeArr[8] = '行业新闻';
$typeArr[9] = '媒体报道';
$typeArr[10] = '专业知识';
$typeArr[11] = '成功案例';
$typeArr[12] = '服务行业';
$typeArr[13] = '教育行业';
$typeArr[14] = '房产行业';
$typeArr[15] = '能源行业';
$typeArr[16] = '服务项目';
$typeArr[17] = '服务项目';
$typeArr[18] = '服务优势';
$typeArr[19] = '服务范畴';
$typeArr[20] = '企业团队';
$typeArr[21] = '设计团队';
$typeArr[22] = '策划团队';
$typeArr[23] = '工程团队';
$typeArr[24] = '管理团队';
$typeArr[25] = '联系我们';
$typeArr[26] = '联系我们';
?>