<?php
$z[0]=Array("field","",20,46);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",104,132);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",134,163);
$z[2][4]['name']="typename";
$z[3]=Array("field","",170,194);
$z[3][4]['name']="typenameen";
$z[4]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",277,415);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>