<figure class="col-xs-12 col-sm-6 col-md-4 col-lg-4"><a href="[field:arcurl/]" title="[field:title/]" class="pic-link" target="_blank"><span class="case-hover"><span class="hover-link"></span></span><img src="[field:picname/]" alt="[field:title/]" class="ylw-img-responsive" alt="[field:title/]" /></a>
        <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a><br />
          <small>关注：[field:click/] / 目录：<a href='[field:typeurl/]'>[field:typename/]</a></small></h3>
      </figure>