<figure class="col-xs-12 col-sm-6 col-md-3 col-lg-3 team-array"><a href="[field:arcurl/]" title="[field:title/]" class="pic-link" target="_blank"><span class="hover-jia"></span><img src="[field:picname/]" alt="[field:title/]" class="img-circle ylw-img-responsive3" alt="[field:title/]" /></a>
          <h3><a href="[field:arcurl/]" target="_blank">[field:title/]</a><br />
            <small>专家设计师<br />
            对于自己一手培育...</small></h3>
        </figure>