<?php
$z[0]=Array("arcurl","",97,112);
$z[1]=Array("title","",121,135);
$z[2]=Array("picname","",265,281);
$z[3]=Array("title","",316,330);
$z[4]=Array("arcurl","",362,377);
$z[5]=Array("title","",386,400);
$z[6]=Array("title","",418,432);
$z[7]=Array("description","",456,506);
$z[7][4]['function']="cn_substr(@me,160)";
$z[8]=Array("typeurl","",554,570);
$z[9]=Array("typename","",572,589);
$z[10]=Array("click","",617,631);
$z[11]=Array("pubdate","",655,702);
$z[11][4]['function']="MyDate('Y-m-d',@me)";

?>