<figure class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <article class="ny-news"><a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="pull-left pic-link visible-lg"><span class="case-hover"><span class="hover-link"></span></span><img src="[field:picname/]" class="ylw-img-responsive2" alt="[field:title/]"/></a>
          <h4><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h4>
          <p>[field:description function="cn_substr(@me,160)"/]...</p>
          <p><span class="fl"><a href='[field:typeurl/]'>[field:typename/]</a></span><span class="gz">[field:click/]</span><span class="sj">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></p>
        </article>
      </figure>