<?php
$z[0]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\">现在致电 0898-688989  OR  查看更多联系方式  &rarr;</a>",65,211);
$z[0][4]['typeid']="25";
$z[1]=Array("type"," <a href=\"[field:typelink/]\" rel=\"nofollow\">现在致电 0898-688989   OR  查看更多联系方式  &rarr;</a>",318,464);
$z[1][4]['typeid']="25";
$z[2]=Array("type"," <a href=\"[field:typelink/]\" class=\"bdsharebuttonbox\" rel=\"nofollow\"><img src=\"/skin/images/fenxiang.png\" width=\"18\" height=\"18\" alt=\"联系我们\" class=\"bds_more\" data-cmd=\"more\"></a>",2475,2695);
$z[2][4]['typeid']="25";
$z[3]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3000,3125);
$z[3][4]['typeid']="3";
$z[4]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3142,3267);
$z[4][4]['typeid']="5";
$z[5]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3284,3410);
$z[5][4]['typeid']="18";
$z[6]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3427,3553);
$z[6][4]['typeid']="19";
$z[7]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3570,3695);
$z[7][4]['typeid']="4";
$z[8]=Array("type","\r\n              <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n              ",3712,3838);
$z[8][4]['typeid']="26";
$z[9]=Array("channel","\r\n              <li><a href=\"[field:typeurl/]\" >[field:typename/]</a></li>\r\n              ",3992,4122);
$z[9][4]['type']="top";
$z[10]=Array("global","",4268,4294);
$z[10][4]['name']="cfg_webname";
$z[11]=Array("global","",4303,4329);
$z[11][4]['name']="cfg_webname";
$z[12]=Array("global","",4660,4686);
$z[12][4]['name']="cfg_powerby";
$z[13]=Array("flink","  [field:link /]  ",6086,6164);
$z[13][4]['titlelen']="20";
$z[13][4]['row']="20";
$z[13][4]['type']="text";
$z[14]=Array("type"," <a href=\"[field:typelink/]\" class=\"kefu-lx\" title=\"[field:typename/]\" target=\"_blank\">[field:typename/]</a>",7224,7367);
$z[14][4]['typeid']="25";

?>