<?php
$z[0]=Array("global","",570,596);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",605,631);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",713,739);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",748,774);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("channelartlist","\r\n        <li class=\"dropdown {dede:field.currentstyle/}\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}<small>{dede:field.typenameen/}</small></a>\r\n          <ul class=\"dropdown-menu dropdown-menu-left\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </li>\r\n        ",1930,2475);
$z[4][4]['typeid']="top";
$z[4][4]['currentstyle']="active";

?>